### ISSUE TITLE
Nanofilt issue

### ISSUE THREAD

**Issue by catch-minie** [wdecoster/nanofilt#1]
Error with Nanofilt also

check command after installation ` NanoFilt -h`
Output
```
Traceback (most recent call last):
  File "/usr/local/bin/NanoFilt", line 7, in <module>
    from nanofilt.NanoFilt import main
  File "/usr/local/lib/python2.7/dist-packages/nanofilt/NanoFilt.py", line 36
    print(record[args.headcrop:args.tailcrop].format("fastq"), end="")
                                                                  ^
SyntaxError: invalid syntax
```

**Comment by wdecoster** [comment]
Hi kminie,

As remarked in the README NanoFilt was written for Python3. And indeed, the end keyword doesn't exist in Python2.7, as such yielding your error.

I don't really plan to write scripts compatible with both versions. Is there a reason you cannot use Python3? If so I might reconsider this.

Cheers,
Wouter

**Comment by wdecoster** [comment]
Hi kminie,

I might have fixed it in version 1.0.4 (https://github.com/wdecoster/nanofilt/commit/7c9a77f87d4c6f46ca1acbdf1f131d74533d3124). Could you try `pip install nanofilt --upgrade` and test again?

Cheers,
Wouter

**Comment by catch-minie** [comment]
Ttried `pip install nanofilt --upgrade` , this is working fine only with `headcrop` or '`tailcrop`' option.
But I want to perform only the quality filter with -q , is there any manual for reference, I can see how headcrop or tailcrop works but  with -q option output is not clear enough. Want to have an example using only quality filter option, basically how it works for each of the base.

**Comment by wdecoster** [comment]
I have added an example to the readme for only filtering on a minimum quality:
```bash
zcat reads.fastq.gz | NanoFilt -q 10 | gzip > highQuality-reads.fastq.gz
```

Reads with an average basecall quality score above 10 will be kept, the rest will be removed. See also my [blog post](https://gigabaseorgigabyte.wordpress.com/2017/06/05/trimming-and-filtering-oxford-nanopore-sequencing-reads/) about the distribution of the quality scores.

It is recommended to repeat the basecalling of your data with the latest albacore, because quality scores are higher then. If you have older basecalls you may have to set a lower cut-off, or first investigate the distribution using [NanoPlot](https://github.com/wdecoster/NanoPlot).
