### ISSUE TITLE
conda version outdated?

### ISSUE THREAD

**Issue by leomrtns** [wdecoster/nanofilt#32]
Hello! I've installed nanofilt with conda (build `bioconda/linux-64::nanofilt-2.2.0-py36_1`); it installs successfully but when calling it, it complains about this line
```python
from nanoget import process_summary
```
(fixing it was easy, just copying from your repo version). Maybe you want to update the conda recipe?
Another small detail: the README.md file might be outdated since it mentions an input file? 

cheers,
leo

**Comment by wdecoster** [comment]
Oh yes, it seems I have to update the conda version. I'll do that. Thanks for letting me know!

The README is not outdated, as since v2.3.0 you can (in addition to stdin, which remains the default) also use an uncompressed fastq file on the command line as input (see also https://github.com/wdecoster/nanofilt/issues/29).

Cheers,
Wouter

**Comment by leomrtns** [comment]
oh cool!
cheers
leo

**Comment by wdecoster** [comment]
It seems the bioconda packages have been updated two days ago: https://github.com/bioconda/bioconda-recipes/pull/15281
So everything should be up to date now :-)

Please let me know if you encounter other issues.
