### ISSUE TITLE
--length and --maxlength in combination with --headcrop and --tailcrop 

### ISSUE THREAD

**Issue by PKuperus** [wdecoster/nanofilt#52]
Hi,
With my nanofilt test run I noticed that --length is executed after  --headcrop and --tailcrop, while --maxlength is done before tail+headcrop.

So with my simple amplicon dataset I did:
cat test.fastq.gz | NanoFilt -q 10 --length 1200 --maxlength 1400 --headcrop 30 --
tailcrop 30 | gzip > test.fastq.gz

I checked the outcome with NanoPlot and the shortest read is 1203bp (selected after tail+headcrop) and the maxlenght read was 1330 (selected before tail+headcrop, read was 1390bp).

Wouldn't it be easier to first select min and mix size and then crop the head and tail...Or is there a reason to do it like NanoFilt does?

Kind regards,
Peter

**Comment by wdecoster** [comment]
Hi Peter,

I agree, that is not terribly consistent, however, not entirely crazy.

To be precise, NanoFilt requires that the read length is longer than the minimum length (--length) + headcrop + tailcrop.
As such it only outputs reads that are > --length also after applying trimming

For --maxlength it currently just requires that the read is shorter than that value, and as such always outputs reads that are shorter than --maxlength (with or without trimming).
What I could do is in this case also output reads that _become_ shorter than --maxlength due to trimming. Would that make sense to you?

The reason to take trimming into account for applying --length is for the corner case of very small reads: if a read is 30bp and you want to trim 15bp from each end, while you want --length 20... then NanoFilt has to reject the read because after trimming, nothing is left.

Cheers,
Wouter
