### ISSUE TITLE
Empty fastq file as output

### ISSUE THREAD

**Issue by eyesmo** [wdecoster/nanofilt#7]
When I try to pipe my fastq files through Nanofilt it spits out an empty (zero bytes) fastq file as output, no matter what filter parameters I set (images attached). Anyone know what I'm doing wrong? Apologies if I'm making a basic mistake; I'm teaching myself sequencing analysis/bioinformatics on the MinION.

What I know:
--I'm using nanofilt version 1.2. 
--reads were basecalled with latest version of albacore
--fastq files were generated by nanopolish, aren't compressed, originally contained several Mb data.
--cat command by itself seems to successfully open the fastq file.
--output fastq file is zero bytes even if no restrictions on quality or length are specified.

![screen shot 2017-10-17 at 12 34 50 am](https://user-images.githubusercontent.com/2289040/31672057-1be68e16-b321-11e7-9ae0-4e49738aabd1.png)

<img width="1119" alt="screen shot 2017-10-17 at 12 34 57 am" src="https://user-images.githubusercontent.com/2289040/31671879-9b6d12d2-b320-11e7-86ce-78c67935c119.png">

<img width="1116" alt="screen shot 2017-10-17 at 9 42 17 am" src="https://user-images.githubusercontent.com/2289040/31672018-f7649bdc-b320-11e7-964b-f93c52f52ed4.png">

<img width="594" alt="screen shot 2017-10-17 at 12 34 16 am" src="https://user-images.githubusercontent.com/2289040/31671890-a2d7ef4c-b320-11e7-96be-1cb6eae73e26.png">

<img width="596" alt="screen shot 2017-10-17 at 12 37 27 am" src="https://user-images.githubusercontent.com/2289040/31671903-aa2c2344-b320-11e7-81d8-94119d6d2d49.png">

**Comment by wdecoster** [comment]
Thanks for reporting this, I will look into this when I get home tomorrow. Puzzling for sure.

**Comment by eyesmo** [comment]
Thanks! I'd be happy to send you the actual fastq file(s) if it would help.

**Comment by wdecoster** [comment]
If possible that would definitely be helpful. You can send the file or maybe a Dropbox link to decosterwouter AT gmail DOT com


Thanks!

**Comment by wdecoster** [comment]
Thanks for sending the file. While I agree that NanoFilt should exit with a sensible error message, I fairly quickly identified the error. You are feeding in a fasta file, rather than a fastq file. I should have seen it in the screenshots above but was on my phone so that's something I missed. Filtering for quality is as such impossible because that information simply isn't there in a fasta file. I could adapt NanoFilt to also work on fasta files for filtering by length or trimming if that would be of interest for you.

But NanoFilt definitely should tell you that your fastq is not really a fastq. I'll look into that, although I would argue that the problem is in biopython, which I use for parsing fastq.

**Comment by wdecoster** [comment]
FYI, I opened an issue about biopython to get a sensible warning when an incorrect input format is used 

https://github.com/biopython/biopython/issues/1410
