### ISSUE TITLE
setup.py looks for README.rst which doesn't exist

### ISSUE THREAD

**Issue by mw55309** [wdecoster/nanofilt#8]
setup.py looks for README.rst which doesn't exist

Fix?

```
ln -s README.md README.rst
```

**Comment by wdecoster** [comment]
Correct me if I'm wrong, but I think this is only an issue when installing from the cloned repo, which indeed doesn't contain the README.rst

The pip and conda installation should be fine.

Prefered fix could be 
`pandoc --from=markdown --to=rst --output=README.rst README.md`
but your solution would probably also work - since setup.py doesn't really use the README.rst and this content is only used for the description on the PyPI website.

I don't keep my README in both .rst and .md but convert to .rst before pushing to PyPI.

**Comment by mw55309** [comment]
Yes, that's right, I cloned from (my forked) github so I could edit and submit pull request.

**Comment by wdecoster** [comment]
So after your pull request, this one is also 'solved'. Thanks again!
